# Generated by Django 6.1.1 on 2026-09-28 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedQuiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(default='Moderate', max_length=50)),
                ('generated_by_llm', models.CharField(default='SETU AI Copilot', max_length=100)),
                ('total_questions', models.IntegerField(default=5)),
                ('passing_score_pct', models.IntegerField(default=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Generated Quiz',
                'verbose_name_plural': 'AI Generated Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source_platform', models.CharField(default='iGOT Karmayogi', max_length=100)),
                ('course_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('duration_hours', models.FloatField(default=10.0)),
                ('course_level', models.CharField(default='Advanced', max_length=50)),
                ('external_url_or_api', models.URLField(blank=True, max_length=500, null=True)),
                ('provider_org', models.CharField(default='iGOT Karmayogi Bharat', max_length=150)),
                ('rating', models.FloatField(default=4.8)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FRACCompetency',
            fields=[
                ('competency_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=150)),
                ('competency_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_scale_level', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'FRAC Competency',
                'verbose_name_plural': 'FRAC Competencies',
            },
        ),
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='onboarding_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('statistical_cadre', models.CharField(default='Indian Statistical Service (ISS)', max_length=150)),
                ('official_designation', models.CharField(blank=True, max_length=150, null=True)),
                ('department_division', models.CharField(blank=True, max_length=150, null=True)),
                ('current_posting_location', models.CharField(blank=True, max_length=150, null=True)),
                ('current_primary_assignment', models.CharField(blank=True, max_length=255, null=True)),
                ('highest_educational_qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('total_years_in_service', models.CharField(blank=True, max_length=50, null=True)),
                ('completed_igot_courses', models.JSONField(blank=True, default=list)),
                ('programmes_attended', models.TextField(blank=True, null=True)),
                ('external_certifications', models.TextField(blank=True, null=True)),
                ('annual_training_hours', models.IntegerField(default=20)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='officer_docs/')),
                ('target_role', models.CharField(blank=True, max_length=150, null=True)),
                ('weekly_learning_budget', models.CharField(default='4 Hours / Week', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCompetencyMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('competency_gain_level', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_mappings', to='authentication.course')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='authentication.fraccompetency')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('verification_code', models.CharField(max_length=100, unique=True)),
                ('score', models.IntegerField(default=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='authentication.course')),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='authentication.fraccompetency')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('role_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='authentication.department')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerQuizAttempt',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('score_obtained', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='authentication.aigeneratedquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('path_id', models.AutoField(primary_key=True, serialize=False)),
                ('path_name', models.CharField(max_length=255)),
                ('ai_rationale', models.TextField(blank=True, null=True)),
                ('total_courses', models.IntegerField(default=1)),
                ('progress_percent', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgSkillAnalyticsSnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('snapshot_period', models.CharField(default='Q3 2026', max_length=50)),
                ('avg_competency_score', models.FloatField(default=80.0)),
                ('critical_skill_deficits', models.IntegerField(default=0)),
                ('total_training_hours', models.FloatField(default=0.0)),
                ('workforce_readiness_index', models.FloatField(default=85.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='authentication.department')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionMCQ',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('ai_explanation', models.TextField(blank=True, null=True)),
                ('mapped_competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.fraccompetency')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='authentication.aigeneratedquiz')),
            ],
        ),
        migrations.CreateModel(
            name='RoleCompetencyRequirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('required_level', models.IntegerField(default=3)),
                ('priority_weight', models.FloatField(default=1.0)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='authentication.fraccompetency')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_requirements', to='authentication.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('gap_id', models.AutoField(primary_key=True, serialize=False)),
                ('required_level', models.IntegerField(default=3)),
                ('current_level', models.IntegerField(default=1)),
                ('gap_score', models.IntegerField(default=0)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('moderate', 'Moderate'), ('mastered', 'Mastered')], default='moderate', max_length=20)),
                ('status', models.CharField(choices=[('unaddressed', 'Unaddressed'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='unaddressed', max_length=20)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skill_gaps', to='authentication.fraccompetency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedLearningMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='PDF', max_length=50)),
                ('file_storage_url', models.FileField(upload_to='learning_materials/')),
                ('extracted_text_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='authentication.fraccompetency')),
                ('uploaded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aigeneratedquiz',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_quizzes', to='authentication.uploadedlearningmaterial'),
        ),
        migrations.CreateModel(
            name='UserCompetencyScore',
            fields=[
                ('user_competency_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_level', models.IntegerField(default=1)),
                ('evaluation_source', models.CharField(default='Diagnostic Assessment', max_length=100)),
                ('last_evaluated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='authentication.fraccompetency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('completion_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('hours_spent', models.FloatField(default=0.0)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('certificate_url', models.URLField(blank=True, max_length=500, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_enrollments', to='authentication.course')),
                ('path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_enrollments', to='authentication.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
