# Generated by Django 6.1.1 on 2026-09-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_aigeneratedquiz_course_department_fraccompetency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(default=False, verbose_name='Onboarding Completed'),
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='Passport Photo / Avatar Data URL'),
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='is_onboarded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='organisation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Subordinate Organisation / Directorate'),
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
